# perguntas = ['qual é a data de pagamento do salário?',
# "sou aprendiz, qual a data de pagamento do salário?",
# "sou temporário, qual a data de pagamento do salário?",
# "Quais documentos preciso enviar para solicitar a auxilio creche?",
# "Tem plano medico?",
# "Hoje meu plabo de saude é bradesco, posso passar para Unimed?",
# "Trabalho na area interna, memo assim tenho direito ao plano odontoprev?",
# "Meus depende tes podem usar o plabo oralgam?",
# "Vc pode enviar o formulario para inclusao junto a Odontoprev por aqui?",
# "Meu seguro de vida tem cobertura para funeral?",
# "Qual o valor do auxilio filhos com deficiencia?",
# "Quero voltar a estudar e soube que a supera tem auxílio educacional, como funciona?",
# "Tenho direito a auxílio creche?",
# "Como faço pra solicitar meu desligamento?",
# "Me explique sobre auxílio filho especial",
# "Como faço o planejamento das minhas férias?",
# "Qual o processo para ter direito a licença paternidade estendida?"]

# perguntas = [
# 'Possuo filhos em condição de creche, eu possuo algum benefício?'
# 'Que documentos preciso enviar?',
# 'Mas filho de qq idade?',
# 'Preciso enviar a nota fiscal da escola?',
# 'A partir de quando posso utilizar?',
# 'Trabalho na area interna, memo assim tenho direito ao plano odontoprev?',
# 'E meus dependentes podem usar esse plano?',
# 'Eu estou cursando uma faculdade relacionada com a minha área, possuo algum benefício?',
# 'Quanto tempo tenho que ficar na empresa?',
# 'Se eu sair antes deste período, o que acontece?',
# 'Quais as regras para participar da previdência privada?',
# 'Qual o Link?',
# 'Desejo pedir demissão',
# 'Como devo solicitar? Uma carta? Existe algum modelo?',
# 'Como fazer uma carta de desligamento?',
# 'Tem algum dia certo pra isso?',
# 'Conte-me sobre o programa de Bolsa de idiomas',
# 'Conte-me sobre os planos odontológicos Supera',
# 'Meus depende tes podem usar o plabo oralgam?',
# 'Quais as regras para participar da previdência privada?',
# 'Qual o Link da previdência privada?',
# 'E o telefone?',
# 'Dúvidas de adesão',
# 'Qual é o orgão responsável por esse programa?',
# 'Qual é o email de contato do brasil prev?',
# 'E qual seria esse site?',
# 'Eu não sei meu período concessivo',
# 'Quero entrar em contato com o RH',
# 'Qual o meu período concessivo?',
# ]

perguntas = ["Sabiá, gostaria de saber sobre o convênio com farmácia",
"quero saber sobre a faixa salarial",
"Quero saber sobre a faixa salarial da farmácia",
"Qual a faixa salarial do benefício de farmácia?",
"qual é a data de pagamento do salário?",
"qual é a data de pagamento mensal?",
"sou aprendiz, qual a data de pagamento do salário?",
"sou temporário, qual a data de pagamento do salário?",
"Quando posso sair de ferias?",
"Qual meu saldo? ",
"Gostaria de saber se sou elegivel ao benefio de auxilio creche",
"Tenho direito ao auxilio creche?",
"Tem idade limite da criança?",
"A partir de quando posso solicitar?",
"Quando posso solicitar o auxilio creche?",
"Que documentos preciso enviar?",
"Quais documentos preciso enviar para solicitar a auxilio creche?",
"Preciso enviar a nota fiscal da escola?",
"Preciso enviar a nota fiscal da escola para solicitar auxilio creche",
"Ate que data recebo o beneficio do auxilio creche?",
"Obrigada pelas informaçoes",
"Tem plano medico?",
"A partir de quando posso utilizar?",
"A partir de quando posso usar o plano de saude?",
"Onde acesso a numeraçao da carteirinha de meu plano de saude?",
"Meus dependentes tem direito ao plano de saude?",
"Posso incluir meus pais jo plano medico?",
"Hoje meu plabo de saude é bradesco, posso passar para Unimed?",
"Qual mimha elegibilidade para mudança de plano de saude?",
"Vc sabe o numero de minha carteirinha do plano de saude?",
"Sabia, qual meu plano odontologico?",
"Trabalho na area interna, memo assim tenho direito ao plano odontoprev?",
"Quem tem direito ao plano oralgam?",
"Meus depende tes podem usar o plabo oralgam?",
"Vc pode enviar o formulario para inclusao junto a Odontoprev por aqui?",
"Tenho seguro de vida?",
"Meu seguro de vida tem cobertura para funeral?",
"Quero receber o auxilio filhos com deficiencia",
"Qual o valor do auxilio filhos com deficiencia?",
"Posso solicitar o auxilio filhos com deficiencia junro com o auxilio creche?",
"Tem idade de limite para solicitar o beneficio filhos com deficiencia?",
"Queria saber como funciona o auxílio educacional",
"Quanto tempo tenho que ficar na empresa?",
"Me referia ao tempo que tenho que ficar na empresa após receber o auxílio educacional",
"Se eu sair antes deste período, o que acontece?",
"Porque seu nome é sabiá?",
"Quais as regras para participar da previdência privada?",
"Qual o Link?",
"Me referia ao link para aderir a previdência privada",
"Qual o link que leva ao Teo?",
"Com quantos % do meu salário posso contribuir na previdência?",
"Quero saber mais",
"Queria saber mais sobre minha faixa salarial específica para previdência",
"Não entendi o que é ur",
"Quando eu posso sair de férias?",
"Qual o meu saldo de férias?",
"Falar com atendente",
"Bom dia",
"Quero voltar a estudar e soube que a supera tem auxílio educacional, como funciona?",
"Posso iniciar o curso a qq momento?",
"Tenho direito a auxílio creche?",
"Mas filho de qq idade?",
"Posso pegar medicamento da supera de graça",
"Como eu posso obter meu funcional card?",
"Como faço pra solicitar meu desligamento?",
"Como devo solicitar? Uma carta? Existe algum modelo?",
"Como fazer uma carta de desligamento?",
"Quero pedir demissão",
"Tem algum dia certo pra isso?",
"Quais cargos são elegíveis ao benefício veículo?",
"Me explique sobre auxílio filho especial",
"Quanto é 90% do salário normativo?",
"Meus pais podem entrar no plano de saúde da supera?",
"Que outras teriam?",
"Quantos dias de licença luto perda do pai",
"Luto",
"Licença nojo",
"Quantos dias de férias eu devo tirar no fim do ano",
"Como faço o planejamento das minhas férias?",
"Qual percentual de desconto do vale alimentação?",
"Após o nascimento do meu filho, tenho quanto tempo  para incluí-lo no plano sem carência?",
"Posso dividir meu período de férias?",
"Qual o processo para ter direito a licença paternidade estendida?",
"Pergunta fora do horário de expediente",
"Quero desligar uma pessoa do meu time, como realizar o desligamento e quais os documentos que devo pedir a assinatura dele?",
"A Supera faz doações para ONGs?",
"Posso indicar um projeto social para a Supera?",
"Como a Supera se envolve com a comunidade em ações sociais e comunitárias?",
"Como saber mais sobre essas iniciativas que a Supera apoia?",
"Como fazer uma comunicação interna dentro da empresa?",
"Quem é a área responsável por fazer as comunicações internas?",
"Quem devo procurar na Supera para temas de ESG?",
"Tenho uma ideia de projeto. Existe algum programa de inovação ou de novas ideias na Supera?",
"Tenho uma ideia de melhoria em um processo interno, quem devo procurar para tratar sobre o tema?",
"Quero indicar um projeto social para a Supera apoiar. Quem devo procurar?",
"Vou dar uma entrevista para um jornalista, preciso de autorização?",
"Posso dar entrevista em nome da Supera?",
"Quero fazer um material com a marca da Supera. Devo envolver qual área?",
"Posso dar brindes e/ou presentes para médicos da minha carteira de clientes?",
"Posso vender produtos da Supera pela internet?",
"Presenciei um caso de assédio e/ou preconceito. O que fazer?",
"Um agente do governo me coagiu e pediu uma quantia em dinheiro. O que fazer?",
"Um produto da Supera está com problemas de qualidade. O que fazer?",
"A Supera tem algum canal de denúncia?",
"A Supera tem algum programa de indicação de talentos?",
"Quais são os benefícios do colaborador com menos de 1 ano de casa?",
"Quais são os benefícios do colaborador com mais de 1 ano de casa?",
"Sou propagandista. Quais são os meus benefícios?",
"Onde vejo a convenção coletiva do meu cargo? Sou farmacêutico e trabalho na área da produção.",
"Você tem uma lista de todos os benefícios da Supera?",
"Fiz 5 anos de Supera, ganho alguma coisa?",
"Fiz 10 anos de Supera, ganho alguma coisa?",
"Qual o canal de ouvidoria para colaboradores da Supera?",
"Tenho 10 anos de Supera e vou ser desligado. Consigo resgatar minha previdência privada com o valor total da contrapartida da empresa?",
"Acho que estou com síndrome do pânico ou burnout. O que eu faço? Quem da Supera pode me ajudar?",
"A Supera tem vagas para pessoas com deficiência? Pessoas pretas?",
"esqueci de marcar o ponto, como corrigir?",
"meu colaborador esqueceu de marcar o ponto, como ajustar?",
"Meu funcionário me entregou um atestado de 5 dias, como proceder?",
"qual email para envio de atestado?",
"Como marcar uma avaliação com o mèdico do trabalho?",
"Fui convocado para a perícia do INSS, como devo proceder com a empresa?",
"Tenho direito a Vale Refeição?",
"Optei por ter Vale alimentação, de qual será meu desconto mensal?",
"qual o último dia que tenho que sair de férias para não dobrar o período?",
"Eu não sei meu período concessivo",
"tenho dia pendentes de férias?",
"quero conversar com o RH",
"Também quero saber sobre reembolso de creche",
"Por quanto tempo posso solicitar o reembolso de idioma?",
"Tenho direito a quantos reembolsos de idioma?",
"Por quantos meses posso solicitar o reembolso de idiomas?",
"Tenho direito a vale transporte?",
"Quero mais detalhes",
"Quero mais detalhes sobre vale transporte",
"Quais as regras para eu receber vale transporte",
"Qual valor tenho direito para vale transporte",
"Como solicitar vale transporte",
"Sabiá, preciso do telefone de contato com a funcional",
"preciso da regra do beneficio de farmácia",
"Falar com atendente",
"Falar com atendente 1 Benefícios",
"Gostaria de informações sobre previdência privada",
"Falar com atendente 1 Benefícios",
"Beneficio academia",
"Sabiá, por favor gostaria de saber as regras para participar do incentivo educacional na Supera",
"Qual procedimento para solicitar licença paternidade?",
"Optando pela extensão da licença paternidade, posso tirar apenas 20 dias invés de 30 dias?",
"Tenho Direito a Vale Refeição",
"Tenho Direito a Vale Alimentação",
"Posso afastar do Trabalho para acompanhamento familiar?",
"Fui mesario nas eleições? qual procedimento?",
"Tenho direito ao auxilio creche",
"Até quantos anos tenho direito ao auxilio creche",
"Como fazer um comunicado? Como realizar uma comunicação? Como pedir um comunicado pro RH? (Quaisquer perguntas com os gatilhos comunicado, comunicação)",
"Perguntas sobre demissão",
"Perguntas sobre material escolar",
"Perguntas sobre dificuldade no acesso ou sem login da SuperaNet",
"Sabia, quem tem direito ao consignado",
"Sabia, como é pago o PRL",
]